disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "DataKube"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "img/datakube-1.png"
description = "Let's build an insanely decent HomeLab with Kubernetes"

  [params.author]
  name = "Your name here"
  email = "youremail@example.com"
  image = "img/oscar.webp"
  imageQuality = 96
  headline = "Linux Guy"
  bio = "Crazy hacker"
  links = [ ]

["params.author"]
name = "Oscar F"
headline = "| DevOps | Runtimes | Kubernetes | CI/CD | AI |"
